---
### tasks specific to OSX

## Packages from vars
- name: Update Homebrew
  homebrew:
    update_homebrew: yes
- name: Install packages with Brew
  homebrew:
    name: "{{ software.brew }}"
- name: Install packages with Brew Cask
  homebrew_cask:
    name: "{{ software.cask }}"
    
## Dock settings
- name: Automatically show and hide Dock
  shell: defaults write com.apple.dock autohide -bool true
- name: Move Dock to left
  shell: defaults write com.apple.dock pinning -string start
  
## Finder settings
- name: List view in Finder by default
  shell: defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
- name: Show extensions in Finder
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
