---
### tasks specific to OSX
- name: Update Homebrew
  homebrew:
    update_homebrew: yes
- name: Install packages with Brew
  homebrew:
    name: "{{ software.common + software.brew }}"
    state: upgraded
- name: Install packages with Brew Cask
  homebrew_cask:
    name: "{{ software.cask }}"
    state: installed
